version:"3.8"
services:
    catalogdb:
        image: mongo
    basketdb:
        image: redis
    discount:
        image: postgres
    identitydb:
        image: mcr.microsoft.com/mssql/server:2019-latest
    orderdb:
        image: mcr.microsoft.com/mssql/server:2019-latest
    rabbitmq:
        image: rabbitmq:3.8.14-management
    catalog.api:
        image: catalop_api_image
        build:
            context: .
            dockerfile: Services/Catalog/FreeEducation.Services.Catalog/Dockerfile
    basket.api:
        image: basket_api_image
        build:
            context: .
            dockerfile: Services/Basket/FreeEducation.Services.Basket/Dockerfile
    photostock.api:
        image: photostock_api_image
        build:
            context: .
            dockerfile: Services/PhotoStock/FreeEducation.Services.PhotoStock/Dockerfile
    discount.api:
        image: discount_api_image
        build:
            context: .
            dockerfile: Services/Discount/FreeEducation.Services.Discount/Dockerfile
    fakepayment.api:
        image: fakepayment_api_image
        build:
            context: .
            dockerfile: Services/FakePayment/FreeEducation.Services.FakePayment/Dockerfile
    order.api:
        image: order_api_image
        build:
            context: .
            dockerfile: Services/Order/FreeEducation.Services.Order.API/Dockerfile
    gateway.api:
        image: gateway_api_image
        build:
            context: .
            dockerfile: Gateways/FreeEducationGateway/Dockerfile
    aspnetcoremvc.web:
        image: aspnetcoremvc.web_image
        build:
            context: .
            dockerfile: Frontend/FreeEducation.Web/Dockerfile      
    identityserver.api:
        image: identityserver_api_image
        build:
            context: .
            dockerfile: IdentityServer/FreeEducation.IdentityServer/Dockerfile
volumes:
    catalogdb_volume:
    discount_volume:
    identitydb_volume:
    orderdb_volume: