version:"3.8"
services:
    catalogdb:
        container_name: catalogdb
        restart: always
        ports:
            -"27017:27017"
        volumes:
            - catalogdb_volume:/data/db
    basketdb:
        container_name: basketdb
        restart: always
        ports:
            -"6379:6379"
    discount:
        container_name: discount
        restart: always
        ports:
            -"5432:5432"
        volumes:
            - discount_volume:/var/lib/postgresql/data
        environment:
           - POSTGRES_USER=admin
           - POSTGRES_PASSWORD=Password1234!
           - POSTGRES_DB=discount 
    identitydb:
        container_name: identitydb
        restart: always
        ports:
            -"1433:1433"
        volumes:
            - identitydb_volume:/var/opt/mssql
        environment:
           - ACCEPT_EULA=Y
           - SA_PASSWORD=Password1234!
    orderdb:
        container_name: orderdb
        restart: always
        ports:
            -"1444:1433"
        volumes:
            - orderdb_volume:/var/opt/mssql
        environment:
           - ACCEPT_EULA=Y
           - SA_PASSWORD=Password1234!
    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            -"5672:5672"
            -"15672:15672"
    catalog.api:
        container_name: catalog.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - RabbitMQURL=rabbitmq
            - IdentityServerURL=http://identityserver.api
            - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
        ports:
            - "5021:80"
        depends_on:
            - catalogdb
    discount.api:
        container_name: discount.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - RabbitMQURL=rabbitmq
            - IdentityServerURL=http://identityserver.api
            - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
        ports:
            - "5024:80"
        depends_on:
            - discount    
    photostock.api:
        container_name: photostock.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - IdentityServerURL=http://identityserver.api
        ports:
            - "5022:80"
        depends_on:
            - type: bind
              source: C:\Users\Umut\Desktop\Photos
              target: /app/wwwroot/photos
    basket.api:
        container_name: catalog.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - IdentityServerURL:http://identityserver.api
            - "ConnectionStrings:PostgreSql=User ID=admin; Password=Password1234!; Server=discount; Port=5432;Database=discountdb;Integrated Security=true;Pooling=true"
        ports:
            - "5023:80"
        depends_on:
            - basketdb
    fakepayment.api:
        container_name: fakepayment.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - IdentityServerURL=http://identityserver.api
            - RabbitMQURL=rabbitmq
        ports:
            - "5016:80"
    order.api:
        container_name: order.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - IdentityServerURL=http://identityserver.api
            - RabbitMQURL=rabbitmq
            - "ConnectionStrings:DefaultConnection=Server=orderdb,1433;Database=orderdb;User=sa;Password=Password1234!"
        ports:
            - "5025:80"
        depends_on:
            - orderdb
    gateway.api:
        container_name: gateway.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - IdentityServerURL=http://identityserver.api
        ports:
            - "5000:80"
    aspnetcoremvc.web:
        container_name: aspnetcoremvc.web
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ServiceApiSettings:IdentityBaseUri=http://identityserver.api
            - ServiceApiSettings:GatewayBaseUri=http://gateway.api
        ports:
            - "5010:80"
        depends_on:
            - gateway.api
            - identityserver.api
            - catalog.api
            - order.api
            - basket.api
            - photostock.api
            - fakepayment.api
            - discount.api
    identityserver.api:
        container_name: identityserver.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=IdentityDb;User=sa;Password=Password1234!"
        ports:
            - "5001:80"
        depends_on:
            - identitydb